src/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_page, name='home_page')
]

src/mount/urls.py
from django.urls import path

from . import views

app_name = 'mounts'
urlpatterns = [
    path('', views.get_mounts, name='mount-index'),
    path('<int:id>/', views.mount_detail, name='mount-detail')
]

src/xiv_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('mounts/', include('mount.urls'), name='mount'),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/home/models.py
from django.db import models

# Create your models here.


class NewsArticle(models.Model):
    title = models.CharField(max_length=200)
    banner = models.CharField(max_length=100)
    html = models.TextField()
    time = models.CharField(max_length=100)
    url = models.CharField(max_length=100)

    def __str__(self):
        return self.title

src/mount/models.py
from django.db import models


class Mount(models.Model):
    id = models.IntegerField(primary_key=True)
    icon = models.CharField(max_length=200)
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=100)

    def __str__(self):
        return self.name

src/ui/models.py
from django.db import models

# Create your models here.

src/home/views.py
import os
import requests
from django.shortcuts import render
from .models import NewsArticle


BASE_URL = 'https://xivapi.com'
API_KEY = os.environ['XIV_API_KEY']


def home_page(request):
    r_news = requests.get(f'{BASE_URL}/lodestone/news?key={API_KEY}')
    r_notices = requests.get(f'{BASE_URL}/lodestone/notices?key={API_KEY}')

    res_news = r_news.json()
    res_notices = r_notices.json()

    news_articles = []
    notices = []

    for article in res_news:
        news_articles.append({
            'banner': article['Banner'],
            'html': article['Html'],
            'time': article['Time'],
            'title': article['Title'],
            'url': article['Url']
        })

    for n in res_notices:
        notices.append({
            'time': n['Time'],
            'title': n['Title'],
            'url': n['Url']
        })

    context = {
        'news_articles': news_articles[:6],
        'notices': notices,
        'key': API_KEY
    }

    return render(request, 'home/home_page.html', context)


def search(request):
    pass

src/mount/views.py
import os
import requests
from django.shortcuts import render
# from django.utils.translation import gettext as _
from .models import Mount

BASE_URL = 'https://xivapi.com'
API_KEY = os.environ['XIV_API_KEY']


def get_mounts(request):
    r = requests.get(f'{BASE_URL}/Mount?key={API_KEY}')
    res = r.json()
    mount_results = res['Results']

    serialized_mount = []

    for m in mount_results:
        if m['Name'] != '':
            Mount.objects.update_or_create(
                id=m['ID'],
                icon=m['Icon'],
                name=m['Name'],
                url=m['Url']
            )
            # mount.save()
        # Mount.objects.filter(id=m['ID']).delete()

    mounts = Mount.objects.order_by('name')
    context = {
        'mounts': mounts
    }
    # print(mounts)

    return render(request, 'mount/index.html', context)


def mount_detail(request, id):
    mount = Mount.objects.get(id=id)
    r = requests.get(f'{BASE_URL}{mount.url}?key={API_KEY}')
    res = r.json()
    vm_mount = {}

    vm_mount['description'] = res['Description']
    vm_mount['name'] = res['Name']
    vm_mount['icon_small'] = res['IconSmall']
    vm_mount['icon'] = res['Icon']

    context = {
        'mount': vm_mount
    }

    return render(request, 'mount/mount_detail.html', context)

src/ui/views.py
from django.shortcuts import render

# Create your views here.

src/templates/base.html
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'ui/css/main.css' %}">
  <link rel="stylesheet" href="{% static 'ui/css/navbar.css' %}">
  {% block css %}
  {% endblock %}
  <title>Magick App</title>
</head>

<body>
  {% include 'partials/_navbar.html' %}
  {% block content %}
  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  {% block js %}
  {% endblock %}
</body>

</html>

src/templates/home/home_page.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'home/css/home_page.css' %}">
{% endblock %}

{% block content %}
<div class="news-container">

  <ul class="news-list">
    {% for a in news_articles %}
    <li id="test_article">
      <a href="https://na.finalfantasyxiv.com{{ a.url }}" class="news-link" target="_new">
        <img src="{{ a.banner }}" alt="banner" width="300">
      </a>
    </li>
    {% endfor %}
  </ul>

  <ul class="news-list">
    {% for n in notices %}
    <li>
      <h3>{{ n.title }}<span>{{ n.time }}</span></h3>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

{% block js %}
<script>
  const API_KEY = "{{ key }}";
</script>
{% endblock %}

src/templates/mount/index.html
{% extends 'base.html' %}

{% block css %}
{% endblock %}

{% block content %}
<h2>Mounts App</h2>
<ul class="mount-list">
  {% for m in mounts %}
  <li>
    <div class="mount-list-item">
      <a href="{% url 'mounts:mount-detail' m.id %}">
        <h2 class="item-name">{{ m.name }}</h2>
      </a>
      <img class="item-url" src="https://xivapi.com{{ m.icon }}" alt="mount" />
    </div>
  </li>

  {% endfor %}
</ul>
{% endblock %}

{% block js %}
{% endblock %}

src/templates/mount/mount_detail.html
{% extends 'base.html' %}

{% block css %}
{% endblock %}

{% block content %}
<h1>{{ mount.name }}</h1>
<img src="https://xivapi.com{{mount.icon}}" alt="icon-small">
<h3>{{ mount.description }}</h3>
{% endblock %}

{% block js %}
{% endblock %}

src/templates/partials/_navbar.html
<nav class="navbar">
  <p class="navbar-brand">Placeholder Inc.</p>
  <span></span>
  <ul class="nav">
    <li class="nav-item">
      <a href="{% url 'home:home_page' %}">Home</a>
    </li>
    <li class="nav-item">
      <a href="#" target="_blank">Link</a>
    </li>
    <li class="nav-item">
      <a href="#" target="_blank">Link</a>
    </li>
  </ul>
</nav>